name = "dash"
compatibility_date = "2024-04-03"
compatibility_flags = ['nodejs_compat']
send_metrics = false
pages_build_output_dir = "./.svelte-kit/cloudflare"

[dev]
port = 8840

# Prod
[[d1_databases]]
binding = "firmlyConfigs"
database_name = "firmly-configs"
database_id = "e6db9dd4-9b04-464f-8d4a-527c256859f3"

[[d1_databases]]
binding = "reporting"
database_name = "reporting"
database_id = "bf2df3ce-3973-4dd4-9fcd-57c11297d57c"

